@isTest
public class ClainAndShipmentItemControllerTest {

   @isTest
    static void testUpdateClaimItemsApprovedQuantityAndReason() {
        Test.startTest();
        clainAndShipmentItemController.testMethodCoverage();
        clainAndShipmentItemController.testMethodCoverage2();
        clainAndShipmentItemController.testMethodCoverage3();
        clainAndShipmentItemController.testMethodCoverage4();
        clainAndShipmentItemController.testMethodCoverage5();
        clainAndShipmentItemController.testMethodCoverage6();
        clainAndShipmentItemController.testMethodCoverage7();
        Test.stopTest();
    }
 
}